### ISSUE TITLE
Ideation

### ISSUE THREAD

**Issue by jchyng** [jchyng/pickbook#1]
아이디어 구체화
- [x] 어떤 문제를 해결하는가?
- [x] 메인 기능은 무엇인가?
- [x] 수익 모델은?
- [x] 확장성이 있는가?

**Comment by jchyng** [comment]
어떤 문제를 해결하는가?

개발 공부를 위해 좋은 책을 찾고싶다
   - 블로그를 일일이 찾아봐야 한다.
   - 도서 판매 사이트에서 개발 도서만 볼 수 있는 카테고리가 없다.

**Comment by SSY1203** [comment]
### 메인 기능은 무엇인가? 

- 개발 서적에 대한 개발 도서 순위를 참고할 수 있다.
- 개발 서적에 대한 후기를 통해 사용자가 공부하고 싶은 분야의 책을 찾을 수 있다.

**Comment by jchyng** [comment]
수익 모델은?
- 책 상세 정보에 책 구매하기 버튼을 통해 구매 시 수수료를 받는다 ( ex. yes24 애드온)
- 사이트 내 광고 유치

**Comment by SSY1203** [comment]
### 확장성이 있는가?

- 캘린더 기능을 통해 독서 기록
- 출판사와 제휴를 맺어 책을 판매
- 전자책을 직접 발매
- 개발자 별 책 로드맵 공유
- 책 중고 거래
- 개발자 커뮤니티
- 학습이 목표인 사용자가 대부분이므로 강의&부트캠프 추천
